name       : yad
version    : '12.0'
release    : 14
source     :
    - https://github.com/v1cont/yad/archive/v12.0.tar.gz : 8f63ccbfda4cb0a0c4f241f667e3e33000295b7067603a7c14029eb7c5668d4e
license    : GPL-3.0-or-later
component  : system.utils
summary    : A tool for creating graphical dialogs from shell scripts
description: |
    YAD (yet another dialog) is a tool for creating graphical dialogs from shell scripts
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    autoreconf -ivf
    intltoolize
    %configure --enable-html \
               --enable-sourceview \
               --enable-spell \
               --with-gtk=gtk3
build      : |
    %make
install    : |
    %make_install
