name       : yad
version    : '13.0'
release    : 18
source     :
    - https://github.com/v1cont/yad/archive/v13.0.tar.gz : 54a2e78e66063573cd081a321e64c03cd1deb18d4e0a27ccaf5f42b3411a4bf5
license    : GPL-3.0-or-later
homepage   : https://github.com/v1cont/yad
component  : system.utils
summary    : A tool for creating graphical dialogs from shell scripts
description: |
    YAD (yet another dialog) is a tool for creating graphical dialogs from shell scripts
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(webkit2gtk-4.0)
    - gettext-devel
setup      : |
    autoreconf -ivf
    intltoolize
    %configure --enable-html \
               --enable-sourceview \
               --enable-spell \
               --with-gtk=gtk3
build      : |
    %make
install    : |
    %make_install
