name       : yad
version    : 0.38.2
release    : 1
source     :
    - https://ufpr.dl.sourceforge.net/project/yad-dialog/yad-0.38.2.tar.xz : 91299cba8836b4e510c4527a081d0ad519ad0c6d9f96b3f7f5409acfb66fd5fa
license    : GPL-3.0
component  : desktop
summary    : A tool for create graphical dialogs from shell scripts
description: |
    YAD (yet another dialog) is a tool for create graphical dialogs from shell scripts
builddeps  :
    - pkgconfig(webkitgtk-3.0)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(gtksourceview-3.0)
setup      : |
    %configure --with-gtk=gtk3 \
               --enable-html \
               --enable-sourceview \
               --enable-spell
build      : |
    %make
install    : |
    %make_install
