name       : yad
version    : '11.1'
release    : 13
source     :
    - https://github.com/v1cont/yad/archive/v11.1.tar.gz : ee57d62e2bfd5672866c87ed71c174fa209e5af74ba6d6384e85f6513ef7541e
license    : GPL-3.0-or-later
component  : system.utils
summary    : A tool for creating graphical dialogs from shell scripts
description: |
    YAD (yet another dialog) is a tool for creating graphical dialogs from shell scripts
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    autoreconf -ivf
    intltoolize
    %configure --enable-html \
               --enable-sourceview \
               --enable-spell \
               --with-gtk=gtk3
build      : |
    %make
install    : |
    %make_install
