name       : yad
version    : '12.3'
release    : 17
source     :
    - https://github.com/v1cont/yad/archive/v12.3.tar.gz : b892813d7f02f984831b92a9b17c0de753bf0721bf1cdc9bb2c70673dca9cc56
license    : GPL-3.0-or-later
component  : system.utils
summary    : A tool for creating graphical dialogs from shell scripts
description: |
    YAD (yet another dialog) is a tool for creating graphical dialogs from shell scripts
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    autoreconf -ivf
    intltoolize
    %configure --enable-html \
               --enable-sourceview \
               --enable-spell \
               --with-gtk=gtk3
build      : |
    %make
install    : |
    %make_install
