name       : yad
version    : 0.40.0
release    : 3
source     :
    - https://netix.dl.sourceforge.net/project/yad-dialog/yad-0.40.0.tar.xz : c2d0b7d1b6d3a0877299faa00db75d58c974f81fce72d520a3a84e67d1d60ef4
license    : GPL-3.0
component  : desktop
summary    : A tool for create graphical dialogs from shell scripts
description: |
    YAD (yet another dialog) is a tool for create graphical dialogs from shell scripts
builddeps  :
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %configure --with-gtk=gtk3 \
               --enable-html \
               --enable-sourceview \
               --enable-spell
build      : |
    %make
install    : |
    %make_install
