name       : yad
version    : '4.1'
release    : 6
source     :
    - https://github.com/v1cont/yad/releases/download/4.1/yad-4.1.tar.xz : cefb18e54542c6aca1957d35aabc1a7ffb78de45d377abed334d4edafcf424a3
license    : GPL-3.0-or-later
component  : system.utils
summary    : A tool for create graphical dialogs from shell scripts
description: |
    YAD (yet another dialog) is a tool for create graphical dialogs from shell scripts
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %configure --enable-html \
        --enable-sourceview \
        --enable-spell \
        --with-gtk=gtk3
build      : |
    %make
install    : |
    %make_install
