name       : yad
version    : 0.39.0
release    : 2
source     :
    - https://netix.dl.sourceforge.net/project/yad-dialog/yad-0.39.0.tar.xz : 11e114c1434f4fa42b2c9a7e6a5f818beead8a697a429906a59fb6f85723a9ed
license    : GPL-3.0
component  : desktop
summary    : A tool for create graphical dialogs from shell scripts
description: |
    YAD (yet another dialog) is a tool for create graphical dialogs from shell scripts
builddeps  :
    - pkgconfig(webkitgtk-3.0)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(gtksourceview-3.0)
setup      : |
    %configure --with-gtk=gtk3 \
               --enable-html \
               --enable-sourceview \
               --enable-spell
build      : |
    %make
install    : |
    %make_install
