name       : yad
version    : '11.0'
release    : 12
source     :
    - https://github.com/v1cont/yad/archive/v11.0.tar.gz : 9226bbd28b05d8c7cf1f5ad4b22bb6f593a7479d9fe36569e231bf2da216295b
license    : GPL-3.0-or-later
component  : system.utils
summary    : A tool for creating graphical dialogs from shell scripts
description: |
    YAD (yet another dialog) is a tool for creating graphical dialogs from shell scripts
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    autoreconf -ivf
    intltoolize
    %configure --enable-html \
               --enable-sourceview \
               --enable-spell \
               --with-gtk=gtk3
build      : |
    %make
install    : |
    %make_install
