name       : yad
version    : '10.1'
release    : 9
source     :
    - https://github.com/v1cont/yad/archive/v10.1.tar.gz : 769e723a8f227ce4430f89fda4c79809ad46fb3c04d34ee466b51cf5e0f1c373
license    : GPL-3.0-or-later
component  : system.utils
summary    : A tool for creating graphical dialogs from shell scripts
description: |
    YAD (yet another dialog) is a tool for creating graphical dialogs from shell scripts
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    autoreconf -ivf
    intltoolize
    %configure --enable-html \
               --enable-sourceview \
               --enable-spell \
               --with-gtk=gtk3
build      : |
    %make
install    : |
    %make_install
